version: "3.8"

services:
  producer:
    build:
      context: app/producer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
    volumes:
      - app/producer:/app
    networks:
      - test-network
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    networks:
      - test-network

networks:
  test-network:
